"""added history with reason

Revision ID: 071cdbf4bf7e
Revises: b9e5fc5fadfe
Create Date: 2025-11-17 15:15:45.782982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071cdbf4bf7e'
down_revision: Union[str, Sequence[str], None] = 'b9e5fc5fadfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_leave_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_emergency_leave_requests_request_id'), 'emergency_leave_requests', ['request_id'], unique=False)
    op.create_table('sick_leave_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_sick_leave_requests_request_id'), 'sick_leave_requests', ['request_id'], unique=False)
    op.create_table('vacation_leave_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_vacation_leave_requests_request_id'), 'vacation_leave_requests', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_leave_requests_request_id'), table_name='vacation_leave_requests')
    op.drop_table('vacation_leave_requests')
    op.drop_index(op.f('ix_sick_leave_requests_request_id'), table_name='sick_leave_requests')
    op.drop_table('sick_leave_requests')
    op.drop_index(op.f('ix_emergency_leave_requests_request_id'), table_name='emergency_leave_requests')
    op.drop_table('emergency_leave_requests')
    # ### end Alembic commands ###
