"""Add IDENTITY to message and conversation primary keys

Revision ID: 70c76c79aaee
Revises: 81e825f67b8f
Create Date: 2025-11-14 16:24:33.301202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c76c79aaee'
down_revision: Union[str, Sequence[str], None] = '81e825f67b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
