"""Add leave type tables

Revision ID: 81e825f67b8f
Revises: 4bfd58625581
Create Date: 2025-11-14 15:29:42.925455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e825f67b8f'
down_revision: Union[str, Sequence[str], None] = '4bfd58625581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_leave',
    sa.Column('emergency_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('used_days', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('GETDATE()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('emergency_id'),
    sa.UniqueConstraint('user_id', name='uq_emergency_user_id')
    )
    op.create_index(op.f('ix_emergency_leave_emergency_id'), 'emergency_leave', ['emergency_id'], unique=False)
    op.create_index(op.f('ix_emergency_leave_user_id'), 'emergency_leave', ['user_id'], unique=True)
    op.create_table('sick_leave',
    sa.Column('sick_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('used_days', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('GETDATE()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sick_id'),
    sa.UniqueConstraint('user_id', name='uq_sick_user_id')
    )
    op.create_index(op.f('ix_sick_leave_sick_id'), 'sick_leave', ['sick_id'], unique=False)
    op.create_index(op.f('ix_sick_leave_user_id'), 'sick_leave', ['user_id'], unique=True)
    op.create_table('vacation_leave',
    sa.Column('vacation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('GETDATE()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vacation_id'),
    sa.UniqueConstraint('user_id', name='uq_vacation_user_id')
    )
    op.create_index(op.f('ix_vacation_leave_user_id'), 'vacation_leave', ['user_id'], unique=True)
    op.create_index(op.f('ix_vacation_leave_vacation_id'), 'vacation_leave', ['vacation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_leave_vacation_id'), table_name='vacation_leave')
    op.drop_index(op.f('ix_vacation_leave_user_id'), table_name='vacation_leave')
    op.drop_table('vacation_leave')
    op.drop_index(op.f('ix_sick_leave_user_id'), table_name='sick_leave')
    op.drop_index(op.f('ix_sick_leave_sick_id'), table_name='sick_leave')
    op.drop_table('sick_leave')
    op.drop_index(op.f('ix_emergency_leave_user_id'), table_name='emergency_leave')
    op.drop_index(op.f('ix_emergency_leave_emergency_id'), table_name='emergency_leave')
    op.drop_table('emergency_leave')
    # ### end Alembic commands ###
