"""added history with reason

Revision ID: b9e5fc5fadfe
Revises: d06e57afb0e4
Create Date: 2025-11-17 15:13:40.222596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e5fc5fadfe'
down_revision: Union[str, Sequence[str], None] = 'd06e57afb0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_leave', 'reason')
    op.drop_column('sick_leave', 'reason')
    op.drop_column('vacation_leave', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_leave', sa.Column('reason', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('sick_leave', sa.Column('reason', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('emergency_leave', sa.Column('reason', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
