"""Added reason for all leaves

Revision ID: d06e57afb0e4
Revises: cfb111ca85ed
Create Date: 2025-11-17 14:25:16.529567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06e57afb0e4'
down_revision: Union[str, Sequence[str], None] = 'cfb111ca85ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_leave', sa.Column('reason', sa.String(length=255), nullable=False))
    op.add_column('sick_leave', sa.Column('reason', sa.String(length=255), nullable=True))
    op.add_column('vacation_leave', sa.Column('reason', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_leave', 'reason')
    op.drop_column('sick_leave', 'reason')
    op.drop_column('emergency_leave', 'reason')
    # ### end Alembic commands ###
